// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BudgetComponent: typeof import('./src/components/BudgetComponent.vue')['default']
    BudgetComponentList: typeof import('./src/components/BudgetComponentList.vue')['default']
    CategoryComponent: typeof import('./src/components/CategoryComponent.vue')['default']
    CategoryComponentList: typeof import('./src/components/CategoryComponentList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EntryComponent: typeof import('./src/components/EntryComponent.vue')['default']
    EntryComponentList: typeof import('./src/components/EntryComponentList.vue')['default']
    ExpenseComponent: typeof import('./src/components/ExpenseComponent.vue')['default']
    ExpenseComponentList: typeof import('./src/components/ExpenseComponentList.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    OperationComponent: typeof import('./src/components/OperationComponent.vue')['default']
    OperationComponentList: typeof import('./src/components/OperationComponentList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SummaryComponent: typeof import('./src/components/SummaryComponent.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
